title: COVID-19 detector in X-rays images
description: Detect COVID-19 in X-rays images
about:
  This is a COVID-19 detector in X-rays images using Deep Learning built with FastAi.


  The project was build by Viridiana Romero


  More info and the source code can be found [here](https://github.com/npatta01/Bird-Classifier)

code: https://github.com/viritaromero/covid19_detector

sampleImages:
  - name: covid19-patient
    url: https://github.com/ieee8023/covid-chestxray-dataset/blob/master/images/1-s2.0-S0929664620300449-gr2_lrg-d.jpg
  - name: covid19-patient
    url: https://github.com/ieee8023/covid-chestxray-dataset/blob/master/images/01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg
  - name: healthy patient
    url: https://www.healthlinkbc.ca/sites/default/libraries/healthwise/media/medical/hw/h9991297_001.jpg
  - name: healthy patient
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Normal_posteroanterior_%28PA%29_chest_radiograph_%28X-ray%29.jpg/1200px-Normal_posteroanterior_%28PA%29_chest_radiograph_%28X-ray%29.jpg
